runtime: nodejs12
service: tr-users-mngr
env_variables:
    PORT: 8080
    apiPath: ''
    databaseHost: '35.192.7.203'
    databasePass: 'Pr0s3gu1r.2709*'
    databasePort: '3306'
    databaseUser: 'root'
    databesePoolAcquiere: '30000'
    databesePoolIdle:  '10000'
    databesePoolMax:  '7'
    databesePoolMin: '0'
    logSentenceSQL: true